### ISSUE TITLE
Path example panics

### ISSUE THREAD

**Issue by xy137** [khonsulabs/easygpu-lyon#1]
After cloning the examples, the path example has panic'd for me with
`thread 'main' panicked at 'buffers that are mapped at creation have to be aligned to COPY_BUFFER_ALIGNMENT'`

**Comment by ecton** [comment]
Apologies for that! I didn't run the Path example after updating easygpu to wgpu 0.6. The newer version enforced a few new buffer size alignments, and apparently, my day-to-day usage of this crate didn't use anything except multiples that worked out perfectly aligned to 4 bytes. 

The fix ended up being in easygpu, and I've published and pushed 0.0.3 of both this library and it. https://github.com/khonsulabs/easygpu/commit/e54941ddf14cc80375bc648a853160d0f64dfd8b

If you update your local copy it should work now. Thanks for checking the project out, let me know if you have any other issues.
